# Don't print a new line at the start of the prompt
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# AWS
[aws]
style = "bold orange"
symbol = "ğŸ…° "
displayed_items = "profile"
disabled = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[time]
style = "bold green"
disabled = true
format = "ğŸ•™[ %T ]"

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_status]
renamed.style = "yellow"
staged.value = "+"
staged.style = "green"
stashed.disabled = true

